version: '3.7'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: logs
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
        # seeding scripts
      #- ./mongo-entrypoint:/docker-entrypoint-initdb.d/init-users.sh      
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  app:
    build: .   
    restart: always
    ports:
      - 8000:5031      
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  mongodb_data_container: